# Generated by Django 3.2.3 on 2021-05-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFeedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
