# Generated by Django 3.2.3 on 2021-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFeedback', '0003_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('nick_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
